package View;

import Model.Func_Class;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author ADMIN
 */
public class ManageUsersForm extends javax.swing.JFrame {

    Model.Users users = new Model.Users();
    Model.Func_Class func = new Model.Func_Class();

    public ManageUsersForm() {
        initComponents();
        this.setLocationRelativeTo(null);

        Border panelHeaderBorder = BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(242, 217, 132));
        jPanel1.setBorder(panelHeaderBorder);

        func.displayIcon(75, 60, "/My_Images/user.png", jLabel_FormTittle);

        func.customTable(jTable_Users);
        func.customTableHeader(jTable_Users, new Color(34, 167, 240), 16);

        jLabel_Empty_FName.setForeground(Color.WHITE);
        jLabel_Empty_LName.setForeground(Color.WHITE);
        jLabel_Empty_Password.setForeground(Color.WHITE);
        jLabel_Empty_Retype_Password.setForeground(Color.WHITE);
        jLabel_Empty_UserName.setForeground(Color.WHITE);
        jLabel_Empty_Phone.setForeground(Color.WHITE);
        jLabel_Empty_Email.setForeground(Color.WHITE);

        populateJTableWithUsers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_FormTittle = new javax.swing.JLabel();
        jLabel_CloseForm = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_FName = new javax.swing.JTextField();
        jButton_Add_ = new javax.swing.JButton();
        jButton_Edit_ = new javax.swing.JButton();
        jButton_Delete_ = new javax.swing.JButton();
        jLabel_Empty_FName = new javax.swing.JLabel();
        jScrollPane_Table = new javax.swing.JScrollPane();
        jTable_Users = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTextField_LName = new javax.swing.JTextField();
        jLabel_Empty_LName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_UserName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_ID = new javax.swing.JTextField();
        jPasswordField_password = new javax.swing.JPasswordField();
        jPasswordField_retypepassword = new javax.swing.JPasswordField();
        jLabel_Empty_UserName = new javax.swing.JLabel();
        jLabel_Empty_Password = new javax.swing.JLabel();
        jLabel_Empty_Retype_Password = new javax.swing.JLabel();
        jCheckBox_UserType = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel_Empty_Email = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel_Empty_Phone = new javax.swing.JLabel();
        jTextField_Email = new javax.swing.JTextField();
        jTextField_Phone = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_FormTittle.setBackground(new java.awt.Color(242, 217, 132));
        jLabel_FormTittle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_FormTittle.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_FormTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_FormTittle.setText("Manage Users");
        jLabel_FormTittle.setOpaque(true);

        jLabel_CloseForm.setBackground(new java.awt.Color(242, 217, 132));
        jLabel_CloseForm.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_CloseForm.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_CloseForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_CloseForm.setText("x");
        jLabel_CloseForm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_CloseForm.setOpaque(true);
        jLabel_CloseForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseFormMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("FIRST NAME");

        jTextField_FName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_FName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_FNameActionPerformed(evt);
            }
        });

        jButton_Add_.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Add_.setText("ADD");
        jButton_Add_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Add_ActionPerformed(evt);
            }
        });

        jButton_Edit_.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Edit_.setText("EDIT");
        jButton_Edit_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Edit_ActionPerformed(evt);
            }
        });

        jButton_Delete_.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Delete_.setText("DELETE");
        jButton_Delete_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Delete_ActionPerformed(evt);
            }
        });

        jLabel_Empty_FName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Empty_FName.setForeground(new java.awt.Color(253, 0, 0));
        jLabel_Empty_FName.setText("* enter the first name");
        jLabel_Empty_FName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Empty_FNameMouseClicked(evt);
            }
        });

        jTable_Users.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTable_Users.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_Users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_UsersMouseClicked(evt);
            }
        });
        jScrollPane_Table.setViewportView(jTable_Users);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("LAST NAME");

        jTextField_LName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_LName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_LNameActionPerformed(evt);
            }
        });

        jLabel_Empty_LName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Empty_LName.setForeground(new java.awt.Color(253, 0, 0));
        jLabel_Empty_LName.setText("* enter the last name");
        jLabel_Empty_LName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Empty_LNameMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("PASSWORD");

        jTextField_UserName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_UserNameActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("USERNAME");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("RETYPE PASSWORD");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("ID");

        jTextField_ID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_ID.setEnabled(false);
        jTextField_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_IDActionPerformed(evt);
            }
        });

        jPasswordField_password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jPasswordField_retypepassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel_Empty_UserName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Empty_UserName.setForeground(new java.awt.Color(253, 0, 0));
        jLabel_Empty_UserName.setText("* enter the user name");
        jLabel_Empty_UserName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Empty_UserNameMouseClicked(evt);
            }
        });

        jLabel_Empty_Password.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Empty_Password.setForeground(new java.awt.Color(253, 0, 0));
        jLabel_Empty_Password.setText("* enter the password");
        jLabel_Empty_Password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Empty_PasswordMouseClicked(evt);
            }
        });

        jLabel_Empty_Retype_Password.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Empty_Retype_Password.setForeground(new java.awt.Color(253, 0, 0));
        jLabel_Empty_Retype_Password.setText("* enter the retype password");
        jLabel_Empty_Retype_Password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Empty_Retype_PasswordMouseClicked(evt);
            }
        });

        jCheckBox_UserType.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox_UserType.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jCheckBox_UserType.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox_UserType.setText("Make This User An Admin");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("EMAIL");

        jLabel_Empty_Email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Empty_Email.setForeground(new java.awt.Color(253, 0, 0));
        jLabel_Empty_Email.setText("* enter the email");
        jLabel_Empty_Email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Empty_EmailMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("NUMBER PHONE");

        jLabel_Empty_Phone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Empty_Phone.setForeground(new java.awt.Color(253, 0, 0));
        jLabel_Empty_Phone.setText("* enter the phone");
        jLabel_Empty_Phone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Empty_PhoneMouseClicked(evt);
            }
        });

        jTextField_Email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_EmailActionPerformed(evt);
            }
        });

        jTextField_Phone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PhoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel_FormTittle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_CloseForm, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Empty_FName, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jTextField_FName, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel9)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Empty_LName, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel3)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPasswordField_retypepassword, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel_Empty_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPasswordField_password, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel_Empty_Retype_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel6)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel_Empty_UserName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel4)
                        .addComponent(jLabel7)
                        .addComponent(jLabel10)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel_Empty_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_LName, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel_Empty_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jTextField_Email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane_Table)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_Add_, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Edit_, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Delete_, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckBox_UserType)
                                .addGap(101, 101, 101)))
                        .addContainerGap(239, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_FormTittle, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(jLabel_CloseForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_FName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Empty_FName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_LName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Empty_LName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Empty_Email)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Empty_Phone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Empty_UserName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordField_password, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Empty_Password)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane_Table))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPasswordField_retypepassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Empty_Retype_Password))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox_UserType)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Add_)
                            .addComponent(jButton_Edit_)
                            .addComponent(jButton_Delete_))))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_CloseFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseFormMouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel_CloseFormMouseClicked

    private void jTextField_FNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_FNameActionPerformed

    }//GEN-LAST:event_jTextField_FNameActionPerformed

    private void jButton_Add_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Add_ActionPerformed
        String fname = jTextField_FName.getText();
        String lname = jTextField_LName.getText();
        String email = jTextField_Email.getText();
        String phone = jTextField_Phone.getText();
        String username = jTextField_UserName.getText();
        String password = String.valueOf(jPasswordField_password.getPassword());
        String retype_password = String.valueOf(jPasswordField_retypepassword.getPassword());
        String userType = "User";

        if (jCheckBox_UserType.isSelected()) {
            userType = "Admin";
        }

        if (lname.trim().isEmpty() && fname.trim().isEmpty() && email.trim().isEmpty() && phone.trim().isEmpty() && username.trim().isEmpty() && password.trim().isEmpty() && retype_password.trim().isEmpty()) {
            jLabel_Empty_FName.setForeground(Color.red);
            jLabel_Empty_LName.setForeground(Color.red);
            jLabel_Empty_Password.setForeground(Color.red);
            jLabel_Empty_Retype_Password.setForeground(Color.red);
            jLabel_Empty_UserName.setForeground(Color.red);
            jLabel_Empty_Phone.setForeground(Color.red);
            jLabel_Empty_Email.setForeground(Color.red);
        } else if (lname.trim().isEmpty()) {
            jLabel_Empty_LName.setForeground(Color.red);
        } else if (fname.trim().isEmpty()) {
            jLabel_Empty_FName.setForeground(Color.red);
        } else if (username.trim().isEmpty()) {
            jLabel_Empty_UserName.setForeground(Color.red);
        } else if (password.trim().isEmpty()) {
            jLabel_Empty_Password.setForeground(Color.red);
        } else if (retype_password.trim().isEmpty()) {
            jLabel_Empty_Retype_Password.setForeground(Color.red);
        } else if (email.trim().isEmpty()) {
            jLabel_Empty_Phone.setForeground(Color.red);
        } else if (phone.trim().isEmpty()) {
            jLabel_Empty_Email.setForeground(Color.red);
        }

        if (!password.equals(retype_password)) {
            JOptionPane.showMessageDialog(null, "Retype The Correct Password", "Password error", 0);
        } else if (users.checkUserNameExists(func.enCode(username))) {
            JOptionPane.showMessageDialog(null, "This UserName Already Exists", "UserName Error", 0);
        } else {
            users.addUser(fname, lname, email, phone, username, password, userType);
        }

        populateJTableWithUsers();
    }//GEN-LAST:event_jButton_Add_ActionPerformed

    private void jButton_Edit_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Edit_ActionPerformed
        int id = Integer.parseInt(jTextField_ID.getText());

        String checkUserName = users.getUserNameSQL(id);
        String checkPassword = users.getPassWordSQL(id);
        String email = jTextField_Email.getText();
        String phone = jTextField_Phone.getText();
        String fname = jTextField_FName.getText();
        String lname = jTextField_LName.getText();
        String username = jTextField_UserName.getText();
        String password = String.valueOf(jPasswordField_password.getPassword());
        String retype_password = String.valueOf(jPasswordField_retypepassword.getPassword());
        String userType = "User";

        if (jCheckBox_UserType.isSelected()) {
            userType = "Admin";
        }

        if (lname.trim().isEmpty() && fname.trim().isEmpty() && email.trim().isEmpty() && phone.trim().isEmpty() && username.trim().isEmpty() && password.trim().isEmpty() && retype_password.trim().isEmpty()) {
            jLabel_Empty_FName.setForeground(Color.red);
            jLabel_Empty_LName.setForeground(Color.red);
            jLabel_Empty_Password.setForeground(Color.red);
            jLabel_Empty_Retype_Password.setForeground(Color.red);
            jLabel_Empty_UserName.setForeground(Color.red);
            jLabel_Empty_Phone.setForeground(Color.red);
            jLabel_Empty_Email.setForeground(Color.red);
        } else if (lname.trim().isEmpty()) {
            jLabel_Empty_LName.setForeground(Color.red);
        } else if (fname.trim().isEmpty()) {
            jLabel_Empty_FName.setForeground(Color.red);
        } else if (username.trim().isEmpty()) {
            jLabel_Empty_UserName.setForeground(Color.red);
        } else if (password.trim().isEmpty()) {
            jLabel_Empty_Password.setForeground(Color.red);
        } else if (retype_password.trim().isEmpty()) {
            jLabel_Empty_Retype_Password.setForeground(Color.red);
        } else if (email.trim().isEmpty()) {
            jLabel_Empty_Phone.setForeground(Color.red);
        } else if (phone.trim().isEmpty()) {
            jLabel_Empty_Email.setForeground(Color.red);
        } else if (!password.equals(retype_password)) {
            JOptionPane.showMessageDialog(null, "Retype The Correct Password", "Password error", 0);
        } else {
            boolean editedUserName = !checkUserName.equals(username);
            boolean editedPassword = !checkPassword.equals(password);
            users.editUser(id, editedUserName, editedPassword, fname, lname, email, phone, username, password, userType);
        }
        populateJTableWithUsers();
    }//GEN-LAST:event_jButton_Edit_ActionPerformed

    private void jButton_Delete_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Delete_ActionPerformed
        try {
            int id = Integer.parseInt(jTextField_ID.getText());
            int confirm = JOptionPane.showConfirmDialog(null, "Are You Sure Delete User", "Confirm Delete User", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                users.removeUser(id);
            }
            populateJTableWithUsers();
            cleanForm();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Invalid User ID - " + ex.getMessage(), "error", 0);
        }
    }//GEN-LAST:event_jButton_Delete_ActionPerformed

    private void jLabel_Empty_FNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Empty_FNameMouseClicked
        jLabel_Empty_FName.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel_Empty_FNameMouseClicked

    private void jTable_UsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_UsersMouseClicked
        int index = jTable_Users.getSelectedRow();
        String id = jTable_Users.getValueAt(index, 0).toString();
        String firstName = jTable_Users.getValueAt(index, 1).toString();
        String lastName = jTable_Users.getValueAt(index, 2).toString();
        String email = jTable_Users.getValueAt(index, 3).toString();
        String phone = jTable_Users.getValueAt(index, 4).toString();
        String userName = jTable_Users.getValueAt(index, 5).toString();
        String passWord = jTable_Users.getValueAt(index, 6).toString();
        String type = jTable_Users.getValueAt(index, 7).toString();

        jTextField_ID.setText(id);
        jTextField_FName.setText(firstName);
        jTextField_LName.setText(lastName);
        jTextField_Email.setText(email);
        jTextField_Phone.setText(phone);
        jTextField_UserName.setText(userName);
        jPasswordField_password.setText(passWord);
        jPasswordField_retypepassword.setText(passWord);
        if (type.equals("Admin")) {
            jCheckBox_UserType.setSelected(true);
        } else if (!type.equals("Admin")) {
            jCheckBox_UserType.setSelected(false);
        }
    }//GEN-LAST:event_jTable_UsersMouseClicked

    private void jTextField_LNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_LNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_LNameActionPerformed

    private void jLabel_Empty_LNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Empty_LNameMouseClicked
        jLabel_Empty_LName.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel_Empty_LNameMouseClicked

    private void jTextField_UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_UserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_UserNameActionPerformed

    private void jTextField_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_IDActionPerformed

    private void jLabel_Empty_UserNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Empty_UserNameMouseClicked
        jLabel_Empty_UserName.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel_Empty_UserNameMouseClicked

    private void jLabel_Empty_PasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Empty_PasswordMouseClicked
        jLabel_Empty_Password.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel_Empty_PasswordMouseClicked

    private void jLabel_Empty_Retype_PasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Empty_Retype_PasswordMouseClicked
        jLabel_Empty_Retype_Password.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel_Empty_Retype_PasswordMouseClicked

    private void jLabel_Empty_EmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Empty_EmailMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_Empty_EmailMouseClicked

    private void jLabel_Empty_PhoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Empty_PhoneMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_Empty_PhoneMouseClicked

    private void jTextField_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_EmailActionPerformed

    private void jTextField_PhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PhoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {

                    //javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageUsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageUsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageUsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageUsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageUsersForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Add_;
    private javax.swing.JButton jButton_Delete_;
    private javax.swing.JButton jButton_Edit_;
    private javax.swing.JCheckBox jCheckBox_UserType;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_CloseForm;
    private javax.swing.JLabel jLabel_Empty_Email;
    private javax.swing.JLabel jLabel_Empty_FName;
    private javax.swing.JLabel jLabel_Empty_LName;
    private javax.swing.JLabel jLabel_Empty_Password;
    private javax.swing.JLabel jLabel_Empty_Phone;
    private javax.swing.JLabel jLabel_Empty_Retype_Password;
    private javax.swing.JLabel jLabel_Empty_UserName;
    private javax.swing.JLabel jLabel_FormTittle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_password;
    private javax.swing.JPasswordField jPasswordField_retypepassword;
    private javax.swing.JScrollPane jScrollPane_Table;
    private javax.swing.JTable jTable_Users;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_FName;
    private javax.swing.JTextField jTextField_ID;
    private javax.swing.JTextField jTextField_LName;
    private javax.swing.JTextField jTextField_Phone;
    private javax.swing.JTextField jTextField_UserName;
    // End of variables declaration//GEN-END:variables

    private void populateJTableWithUsers() {
        ArrayList<Model.Users> usersList = users.usersList();

        String[] colNames = {"ID", "F-Name", "L-Name", "Email", "Phone", "UserName", "Password", "Type"};
        Object[][] rows = new Object[usersList.size()][colNames.length];

        for (int i = 0; i < usersList.size(); i++) {
            rows[i][0] = usersList.get(i).getId();
            rows[i][1] = usersList.get(i).getFirstName();
            rows[i][2] = usersList.get(i).getLastName();
            rows[i][3] = usersList.get(i).getEmail();
            rows[i][4] = usersList.get(i).getNumberPhone();
            rows[i][5] = usersList.get(i).getUserName();
            rows[i][6] = usersList.get(i).getPassword();
            rows[i][7] = usersList.get(i).getUserType();
        }

        DefaultTableModel model = new DefaultTableModel(rows, colNames);
        jTable_Users.setModel(model);

        // Set column widths after setting the model
        int[] widths = {50, 100, 100, 150, 70, 100, 100, 50};
        for (int i = 0; i < widths.length; i++) {
            TableColumn column = jTable_Users.getColumnModel().getColumn(i);
            column.setPreferredWidth(widths[i]);
        }
    }

    public void cleanForm() {
        jTextField_ID.setText("");
        jTextField_FName.setText("");
        jTextField_LName.setText("");
        jTextField_Email.setText("");
        jTextField_Phone.setText("");
        jCheckBox_UserType.setSelected(false);
        jTextField_UserName.setText("");
        jPasswordField_password.setText("");
        jPasswordField_retypepassword.setText("");
    }
}
