package View;

import Model.Func_Class;
import Model.Issue_Book;
import Model.Member;
import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.SQLException;
import java.text.ParseException;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author ADMIN
 */
public class ReturnBookForm extends javax.swing.JFrame {

    /**
     * Creates new form MembersListForm
     */
    Model.Issue_Book issue = new Issue_Book();
    Model.Book book = new Model.Book();
    Model.Member member = new Model.Member();
    Model.Func_Class func = new Model.Func_Class();
    Model.Genre genre = new Model.Genre();
    HashMap<String, Integer> genresMap = genre.getGenresMap();

    boolean book_Exist = false;
    boolean member_Exist = false;

    public ReturnBookForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        Border panelHeaderBorder = BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(108, 122, 137));
        jPanel1.setBorder(panelHeaderBorder);
        func.displayIcon(80, 40, "/My_Images/organizer.png", jLabel_FormTittle);

        setBorderToJlabel(jLabel_BookName_, Color.WHITE);
        setBorderToJlabel(jLabel_MemberFullName_, Color.WHITE);

        Border JlabelIamgeHeaderBorder = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(0, 0, 0));

        jDateChooser_IssueDate.setFont(new Font("Tahoma", 0, 18));
        jDateChooser_ReturnDate.setFont(new Font("Tahoma", 0, 18));

        func.customTable(jTable_IssueBook_);

        func.customTableHeader(jTable_IssueBook_, new Color(34, 167, 240), 15);

        populateJTableWithIssueBook("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_FormTittle = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton_Return_ = new javax.swing.JButton();
        jButton_Lost_ = new javax.swing.JButton();
        jDateChooser_IssueDate = new com.toedter.calendar.JDateChooser();
        jButton_SearchBook_ = new javax.swing.JButton();
        jLabel_BookName_ = new javax.swing.JLabel();
        jLabel_MemberFullName_ = new javax.swing.JLabel();
        jButton_SearchMember_ = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jDateChooser_ReturnDate = new com.toedter.calendar.JDateChooser();
        jSpinner_BookID = new javax.swing.JSpinner();
        jSpinner_MemberID = new javax.swing.JSpinner();
        jLabel_CloseForm = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_IssueBook_ = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jComboBox_SelectStatus = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_Note = new javax.swing.JTextArea();
        jButton_Delete_ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_FormTittle.setBackground(new java.awt.Color(108, 122, 137));
        jLabel_FormTittle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_FormTittle.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_FormTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_FormTittle.setText("Issue Book");
        jLabel_FormTittle.setOpaque(true);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Enter Book ID");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Enter Member ID");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Issue Date");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton_Return_.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_Return_.setText("Return");
        jButton_Return_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Return_ActionPerformed(evt);
            }
        });

        jButton_Lost_.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_Lost_.setText("Lost");
        jButton_Lost_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Lost_ActionPerformed(evt);
            }
        });

        jDateChooser_IssueDate.setEnabled(false);

        jButton_SearchBook_.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jButton_SearchBook_.setText("Search Book");
        jButton_SearchBook_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SearchBook_ActionPerformed(evt);
            }
        });

        jLabel_BookName_.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel_BookName_.setForeground(new java.awt.Color(102, 102, 255));
        jLabel_BookName_.setText("Book Name");
        jLabel_BookName_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_BookName_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_BookName_MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_BookName_MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_BookName_MouseExited(evt);
            }
        });

        jLabel_MemberFullName_.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel_MemberFullName_.setForeground(new java.awt.Color(102, 102, 255));
        jLabel_MemberFullName_.setText("Member Full-Name");
        jLabel_MemberFullName_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_MemberFullName_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MemberFullName_MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_MemberFullName_MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_MemberFullName_MouseExited(evt);
            }
        });

        jButton_SearchMember_.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jButton_SearchMember_.setText("Search Member");
        jButton_SearchMember_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SearchMember_ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Return Date");

        jSpinner_BookID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jSpinner_BookID.setEnabled(false);

        jSpinner_MemberID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jSpinner_MemberID.setEnabled(false);

        jLabel_CloseForm.setBackground(new java.awt.Color(108, 122, 137));
        jLabel_CloseForm.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_CloseForm.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_CloseForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_CloseForm.setText("x");
        jLabel_CloseForm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_CloseForm.setOpaque(true);
        jLabel_CloseForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseFormMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Note");

        jTable_IssueBook_.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable_IssueBook_.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_IssueBook_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_IssueBook_MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_IssueBook_);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Select Book Status");

        jComboBox_SelectStatus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox_SelectStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Issued", "Returned", "Lost" }));
        jComboBox_SelectStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_SelectStatusActionPerformed(evt);
            }
        });

        jTextArea_Note.setColumns(20);
        jTextArea_Note.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextArea_Note.setRows(5);
        jScrollPane2.setViewportView(jTextArea_Note);

        jButton_Delete_.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_Delete_.setText("Delete");
        jButton_Delete_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Delete_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jDateChooser_ReturnDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jDateChooser_IssueDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel5))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_BookName_)
                            .addComponent(jLabel_MemberFullName_)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSpinner_BookID, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(jSpinner_MemberID))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton_SearchBook_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_SearchMember_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_Return_, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Delete_, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Lost_, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_SelectStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel_FormTittle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_CloseForm, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_FormTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_CloseForm, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinner_BookID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_SearchBook_)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_BookName_)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton_SearchMember_)
                                    .addComponent(jSpinner_MemberID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_MemberFullName_)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser_IssueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser_ReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton_Return_)
                                    .addComponent(jButton_Lost_)
                                    .addComponent(jButton_Delete_)))
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox_SelectStatus)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jLabel_CloseFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseFormMouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel_CloseFormMouseClicked

    private void jButton_Lost_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Lost_ActionPerformed
        int book_id = (int) jSpinner_BookID.getValue();
        int member_id = (int) jSpinner_MemberID.getValue();
        String note = jTextArea_Note.getText();

        SimpleDateFormat dateForm = new SimpleDateFormat("yyyy-MM-dd");
        try {
            String return_date = dateForm.format(jDateChooser_ReturnDate.getDate());

            String issue_date = dateForm.format(jDateChooser_IssueDate.getDate());

            issue.updateIssue(book_id, member_id, "Lost", issue_date, return_date, note);

            int quantity = new Model.Book().getBookById(book_id).getQuantity();
            book.setQuantity_Minus_One(book_id, quantity - 1);

            jSpinner_BookID.setValue(0);
            jSpinner_MemberID.setValue(0);
            jLabel_BookName_.setText("Book Name");
            jLabel_MemberFullName_.setText("Member Full-Name");

            jDateChooser_IssueDate.setDate(null);
            jDateChooser_ReturnDate.setDate(null);
            jTextArea_Note.setText("");

        } catch (HeadlessException | NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Select An Item From The Table", "Select Item", 2);
        } catch (SQLException ex) {
            Logger.getLogger(ReturnBookForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        populateJTableWithIssueBook("");
    }//GEN-LAST:event_jButton_Lost_ActionPerformed

    private void jButton_Return_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Return_ActionPerformed
        int book_id = (int) jSpinner_BookID.getValue();
        int member_id = (int) jSpinner_MemberID.getValue();
        String note = jTextArea_Note.getText();

        SimpleDateFormat dateForm = new SimpleDateFormat("yyyy-MM-dd");
        try {
            String return_date = dateForm.format(jDateChooser_ReturnDate.getDate());
            Date returnDate = dateForm.parse(return_date);

            String issue_date = dateForm.format(jDateChooser_IssueDate.getDate());
            Date issueDate = dateForm.parse(issue_date);

            if (returnDate.before(issueDate)) {
                JOptionPane.showMessageDialog(null, "The Return Date Must Be After The Issue Date", "Wrong Return Date", 2);
            } else {
                issue.updateIssue(book_id, member_id, "Returned", issue_date, return_date, note);
                jSpinner_BookID.setValue(0);
                jSpinner_MemberID.setValue(0);
                jLabel_BookName_.setText("Book Name");
                jLabel_MemberFullName_.setText("Member Full-Name");

                jDateChooser_IssueDate.setDate(null);
                jDateChooser_ReturnDate.setDate(null);
                jTextArea_Note.setText("");
            }
        } catch (HeadlessException | NullPointerException | ParseException e) {
            JOptionPane.showMessageDialog(null, "Select An Item From The Table", "Select Item", 2);
        }
        populateJTableWithIssueBook("");
    }//GEN-LAST:event_jButton_Return_ActionPerformed

    private void jButton_SearchBook_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SearchBook_ActionPerformed
//        int book_id = (int) jSpinner_BookID.getValue();
//        try {
//            Model.Book selectedBook = book.getBookById(book_id);
//            if (selectedBook != null) {
//                jLabel_BookName_.setText(selectedBook.getName());
//                book_Exist = true;
//
//                if (issue.checkBookAvailability(book_id)) {
//                    jLabel_Available.setText("YES");
//                    jLabel_Available.setForeground(Color.GREEN);
//                } else {
//                    jLabel_Available.setText("NO");
//                    jLabel_Available.setForeground(Color.red);
//                }
//
//            } else {
//                JOptionPane.showMessageDialog(null, "This book doesn't exist", "Book Not Found", 2);
//                jLabel_BookName_.setText("Book Name");
//                book_Exist = false;
//                jLabel_Available.setText("YES/NO");
//                jLabel_Available.setForeground(new Color(0, 51, 204));
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(ReturnBookForm.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_jButton_SearchBook_ActionPerformed

    private void jButton_SearchMember_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SearchMember_ActionPerformed
        int member_id = (int) jSpinner_MemberID.getValue();
        try {
            Model.Member selectedMember = member.getMemberById(member_id);
            if (selectedMember != null) {
                jLabel_MemberFullName_.setText(selectedMember.getFistName() + " " + selectedMember.getLastName());
                member_Exist = true;
            } else {
                JOptionPane.showMessageDialog(null, "This member doesn't exist", "Member Not Found", 2);
                jLabel_MemberFullName_.setText("Member-Full-Name");
                member_Exist = false;
            }
        } catch (SQLException ex) {
            Logger.getLogger(ReturnBookForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_SearchMember_ActionPerformed

    private void jLabel_BookName_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_BookName_MouseClicked

        int book_id = (int) jSpinner_BookID.getValue();
        BookInfoCardForm bookInfoCardForm = new BookInfoCardForm(book_id);
        bookInfoCardForm.setVisible(true);
    }//GEN-LAST:event_jLabel_BookName_MouseClicked

    private void jLabel_MemberFullName_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MemberFullName_MouseClicked
        int member_id = (int) jSpinner_MemberID.getValue();
        MemberInfoCardForm memberInfoCardForm = new MemberInfoCardForm(member_id);
        memberInfoCardForm.setVisible(true);
    }//GEN-LAST:event_jLabel_MemberFullName_MouseClicked

    private void jLabel_BookName_MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_BookName_MouseEntered
        setBorderToJlabel(jLabel_BookName_, new Color(51, 102, 255));
    }//GEN-LAST:event_jLabel_BookName_MouseEntered

    private void jLabel_BookName_MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_BookName_MouseExited

        setBorderToJlabel(jLabel_BookName_, new Color(255, 255, 255));
    }//GEN-LAST:event_jLabel_BookName_MouseExited

    private void jLabel_MemberFullName_MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MemberFullName_MouseEntered
        setBorderToJlabel(jLabel_MemberFullName_, new Color(51, 102, 255));
    }//GEN-LAST:event_jLabel_MemberFullName_MouseEntered

    private void jLabel_MemberFullName_MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MemberFullName_MouseExited
        setBorderToJlabel(jLabel_MemberFullName_, new Color(255, 255, 255));
    }//GEN-LAST:event_jLabel_MemberFullName_MouseExited

    private void jComboBox_SelectStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_SelectStatusActionPerformed
        String status = jComboBox_SelectStatus.getSelectedItem().toString();
        if (status.equals("All")) {
            status = "";
        }
        populateJTableWithIssueBook(status);
    }//GEN-LAST:event_jComboBox_SelectStatusActionPerformed

    private void jTable_IssueBook_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_IssueBook_MouseClicked
        int index = jTable_IssueBook_.getSelectedRow();

        int book_id = Integer.parseInt(jTable_IssueBook_.getValueAt(index, 0).toString());
        int member_id = Integer.parseInt(jTable_IssueBook_.getValueAt(index, 1).toString());

        Model.Book selectedBook;
        Model.Member selectedMember;

        try {
            selectedBook = book.getBookById(book_id);
            jSpinner_BookID.setValue(selectedBook.getId());
            jLabel_BookName_.setText(selectedBook.getName());

            selectedMember = member.getMemberById(member_id);
            jSpinner_MemberID.setValue(selectedMember.getId());
            jLabel_MemberFullName_.setText(selectedMember.getFistName() + " " + selectedMember.getLastName());

            String issue_date = jTable_IssueBook_.getValueAt(index, 3).toString();
            String return_date = jTable_IssueBook_.getValueAt(index, 4).toString();
            //String status = jTable_IssueBook_.getValueAt(index, 4).toString();
            String note = jTable_IssueBook_.getValueAt(index, 5).toString();

            Date issDate = new SimpleDateFormat("yyyy-MM-dd").parse(issue_date);
            jDateChooser_IssueDate.setDate(issDate);

            Date rtnDate = new SimpleDateFormat("yyyy-MM-dd").parse(return_date);
            jDateChooser_ReturnDate.setDate(rtnDate);

            jTextArea_Note.setText(note);

        } catch (SQLException ex) {
            Logger.getLogger(ReturnBookForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(ReturnBookForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTable_IssueBook_MouseClicked

    private void jButton_Delete_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Delete_ActionPerformed

        int index = jTable_IssueBook_.getSelectedRow();

        try {

            int book_id = Integer.parseInt(jTable_IssueBook_.getValueAt(index, 0).toString());
            int member_id = Integer.parseInt(jTable_IssueBook_.getValueAt(index, 1).toString());

            String issued_date = jTable_IssueBook_.getValueAt(index, 3).toString();

            issue.removeFromIssue(book_id, member_id, issued_date);
            populateJTableWithIssueBook("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Select The Element You Want To Delete From The Table" + e.getMessage(), "Select Item", 2);
        }


    }//GEN-LAST:event_jButton_Delete_ActionPerformed

    public void setBorderToJlabel(JLabel label, Color color) {
        Border border = BorderFactory.createMatteBorder(0, 0, 1, 0, color);
        label.setBorder(border);
    }

    public void populateJTableWithIssueBook(String status) {
        ArrayList<Model.Issue_Book> issueBookList = issue.issuedBooksList(status);

        String[] colNames = {"Book", "Member", "Status", "Iss-Date", "Rtn-Date", "Note"};

        Object[][] rows = new Object[issueBookList.size()][colNames.length];

        for (int i = 0; i < issueBookList.size(); i++) {
            rows[i][0] = issueBookList.get(i).getBook_id();
            rows[i][1] = issueBookList.get(i).getMember_id();
            rows[i][2] = issueBookList.get(i).getStatus();
            rows[i][3] = issueBookList.get(i).getIssue_date();
            rows[i][4] = issueBookList.get(i).getReturn_date();
            rows[i][5] = issueBookList.get(i).getNote();
        }
        DefaultTableModel model = new DefaultTableModel(rows, colNames);
        jTable_IssueBook_.setModel(model);

        int[] widths = {70, 150, 150, 150, 150, 100};
        for (int i = 0; i < widths.length; i++) {
            TableColumn column = jTable_IssueBook_.getColumnModel().getColumn(i);
            column.setPreferredWidth(widths[i]);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    //javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBookForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Delete_;
    private javax.swing.JButton jButton_Lost_;
    private javax.swing.JButton jButton_Return_;
    private javax.swing.JButton jButton_SearchBook_;
    private javax.swing.JButton jButton_SearchMember_;
    private javax.swing.JComboBox<String> jComboBox_SelectStatus;
    private com.toedter.calendar.JDateChooser jDateChooser_IssueDate;
    private com.toedter.calendar.JDateChooser jDateChooser_ReturnDate;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_BookName_;
    private javax.swing.JLabel jLabel_CloseForm;
    private javax.swing.JLabel jLabel_FormTittle;
    private javax.swing.JLabel jLabel_MemberFullName_;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner_BookID;
    private javax.swing.JSpinner jSpinner_MemberID;
    private javax.swing.JTable jTable_IssueBook_;
    private javax.swing.JTextArea jTextArea_Note;
    // End of variables declaration//GEN-END:variables
}
